sudo: required
language: python
python:
   - "3.6"

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - llvm-6.0-dev
      - clang-6.0
      - gcc-7
      - g++-7
env:
  global:
      - CXX="g++-7 -v" CC=gcc-7

before_install:
   - pip install onnx

install:
   - wget -qO- https://buildbot.halide-lang.org/halide-linux-64-gcc53-trunk-50c8577a045a1da1c670c9c9199cfc0889a7282b.tgz | tar xvz
   - pip install -e .

script:
   - HALIDE_DIR=halide python3 scripts/test_onnx_backend.py